/** Accroches slide 1 — banque statique, sans API. */
export const HOOKS_BANK: string[] = [
  "J'ai failli lâcher cette année.",
  "Personne m'avait dit ça en prépa.",
  "Je pensais être nul. J'avais tort.",
  "3 mois sans réviser = catastrophe.",
  "Mon pire trimestre m'a tout appris.",
  "Stop relire tes cours en boucle.",
  "La veille de partiel j'étais perdu.",
  "J'ai arrêté de réviser 6 heures d'affilée.",
  "Mon secret pour tenir la rentrée.",
  "Je croyais connaître mes cours. Non.",
  "La méthode que j'aurais aimé connaître avant.",
  "Pourquoi tes notes stagnent depuis des mois.",
  "J'ai testé tout. Voici ce qui marche.",
  "Ton cerveau n'est pas le problème.",
  "La galère que personne montre sur TikTok.",
  "J'ai failli redoubler. Voici mon fix.",
  "Réviser ≠ relire. Point.",
  "Ce que les majors font différemment.",
  "J'étais épuisé avant les exams.",
  "Une habitude qui a changé mes notes.",
  "Stop te comparer aux autres.",
  "Tu révises mal depuis le lycée.",
  "Mon erreur n°1 en fac.",
  "3 semaines avant le partiel j'ai paniqué.",
  "La technique que mes profs n'ont jamais dite.",
  "J'ai arrêté le surmenage. Résultat :",
  "Pourquoi tu oublies tout en 48h.",
  "La vérité sur les révisions de dernière minute.",
  "J'ai enfin compris comment retenir.",
  "Ton système de révision est cassé.",
  "Ce hack m'a sauvé le semestre.",
  "Je ne suis pas plus intelligent. Juste mieux organisé.",
  "La galère du contrôle surprise.",
  "Pourquoi je ne fais plus de nuit blanche.",
  "Mon avant / après en révision.",
  "Si tu procrastines, lis ça.",
  "J'ai perdu 2 semaines à rien faire.",
  "La méthode anti-stress que j'utilise.",
  "Personne ne te dit ça sur les partiels.",
  "J'ai changé une chose. Tout a basculé.",
  "Tu mérites de t'en sortir.",
  "Mon plan quand j'ai 0 motivation.",
  "Stop croire que t'es pas fait pour ça.",
  "La routine de 20 min qui suffit.",
  "J'étais à 8 de moyenne. Voici la suite.",
  "Ce que j'aurais fait dès la L1.",
  "Tu n'es pas seul dans cette galère.",
  "La leçon que m'a apprise un échec.",
  "Pourquoi tes fiches ne servent à rien.",
  "J'ai simplifié ma vie d'étudiant.",
  "Le conseil que je donnerais à mon moi de l'an passé.",
];

export function pickRandomHook(): string {
  return HOOKS_BANK[Math.floor(Math.random() * HOOKS_BANK.length)];
}
